name: Deploy Flask App to Azure

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: flaskidqkbkqkfcbzi  # must match Bicep app name param
  AZURE_RESOURCE_GROUP: cicdrgcentral
  AZURE_REGION: CentralUS 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

 #   - name: 'Deploy Infrastructure using Bicep'
  #    uses: azure/arm-deploy@v1
   #   with:
    #    subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
     #   resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
      #  template: ./deploy.bicep
       # parameters: location=${{ env.AZURE_REGION }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
